[project]
name = "mcp-epo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp[studio]>=2.10.6",
    "mcp[cli]>=1.12.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
]
